version: '3.7'

services:
  db:
    image: 'postgres:latest'
    container_name: read-stock-db
    ports:
      - 15432:5432
    env_file:
      - .env_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
volumes:
  postgres_data: