FROM python:3.8-slim-buster

WORKDIR /python-docker

RUN pip3 install flask
RUN pip3 install python-dotenv
RUN pip3 install psycopg2-binary

COPY . .

EXPOSE 5006
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5006"]