version: '3.7'

services:
  app:
      image: 'amaleno/node:readcountriesapi'
      container_name: read-countries-api
      ports:
        - 5006:5006
  db:
    image: 'postgres:latest'
    container_name: read-countries-db
    ports:
      - 15432:5432
    env_file:
      - .env_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
volumes:
  postgres_data: